'use client';

import { useEffect, useMemo, useState } from 'react';

const exercises = [
  { id:'dead-bug', name:'Dead Bug', dose:'6 each side', setup:'Lie on your back with arms up and knees bent to 90°.', cue:'Keep your lower back gently heavy against the floor. Move slowly.', avoid:'Do not let the lower back arch as your arm and leg extend.', easier:'Move one arm or leg at a time.', focus:'Deep core', art:'deadbug', image:'/exercise-deadbug.png?v=core-image-fix-1' },
  { id:'glute-bridge', name:'Glute Bridge', dose:'10 reps', setup:'Lie on your back with knees bent and feet flat on the floor.', cue:'Brace lightly, squeeze your glutes, then lift until your body forms a straight line.', avoid:'Do not finish by over-arching your lower back.', easier:'Lift only a few centimetres.', focus:'Glutes + core', art:'bridge', image:'/exercise-bridge.png?v=core-image-fix-1' },
  { id:'bird-dog', name:'Bird Dog', dose:'6 each side', setup:'Start on hands and knees with hands under shoulders.', cue:'Reach long through the opposite arm and leg while keeping your hips level.', avoid:'Do not rotate your pelvis or crank your leg too high.', easier:'Keep your toes on the floor and move one limb at a time.', focus:'Core stability', art:'birddog', image:'/exercise-birddog.png?v=core-image-fix-1' },
  { id:'side-plank-knees', name:'Side Plank — Knees', dose:'20 sec each side', timer:20, timerRounds:2, setup:'Lie on your side with knees bent and elbow under your shoulder.', cue:'Keep shoulders, hips and knees in one line. Lift from the underside waist.', avoid:'Do not let the top shoulder roll forward.', easier:'Lift only a few centimetres.', focus:'Side core', art:'sideplank', image:'/exercise-sideplank.png?v=core-image-fix-1' },
  { id:'heel-taps', name:'Heel Taps', dose:'8 each side', setup:'Lie on your back with knees bent and feet lifted.', cue:'Keep ribs relaxed and slowly tap one heel away without losing trunk position.', avoid:'Shorten the range if your lower back starts to arch.', easier:'Tap closer to your body.', focus:'Abs control', art:'heeltap', image:'/exercise-heeltap.png?v=core-image-fix-1' },
  { id:'forearm-plank', name:'Forearm Plank', dose:'20 sec', timer:20, timerRounds:1, setup:'Set your forearms under your shoulders with legs extended.', cue:'Press the forearms into the mat and keep your body in one straight line.', avoid:'Do not let your hips sag or pike upward.', easier:'Keep your knees on the mat.', focus:'Core stability', art:'plank', image:'/exercise-plank.png?v=core-image-fix-1' },
  { id:'crunch', name:'Abdominal Crunch', dose:'10 reps', setup:'Lie on your back with knees bent and feet flat.', cue:'Curl your upper back gently while keeping your neck relaxed and chin slightly tucked.', avoid:'Do not pull on your neck or use momentum.', easier:'Lift your head and shoulders less.', focus:'Abdominal control', art:'crunch', image:'/exercise-crunch.png?v=core-image-fix-1' },
  { id:'reverse-crunch', name:'Reverse Crunch', dose:'10 reps', setup:'Lie on your back with knees bent and arms by your sides.', cue:'Curl your pelvis gently toward your ribs and lower back down with control.', avoid:'Do not swing your legs or lift your head and shoulders.', easier:'Lift your pelvis only slightly.', focus:'Lower abs', art:'reversecrunch', image:'/exercise-reversecrunch.png?v=core-image-fix-1' },
  { id:'hollow-hold', name:'Hollow Hold', dose:'20 sec', timer:20, timerRounds:1, setup:'Lie on your back with ribs down and legs extended.', cue:'Keep your ribs down and hold the position without letting your lower back lift.', avoid:'Bend your knees or shorten the lever if your back arches.', easier:'Bend your knees and keep arms by your sides.', focus:'Deep core', art:'hollowhold', image:'/exercise-hollowhold.png?v=core-image-fix-1' },
  { id:'lying-leg-raise', name:'Lying Leg Raise', dose:'8 reps', setup:'Lie on your back with legs straight and arms by your sides.', cue:'Lower straight legs slowly while keeping your lower back controlled against the mat.', avoid:'Do not swing your legs or arch your lower back.', easier:'Bend your knees as you lower.', focus:'Lower abs', art:'legraise', image:'/exercise-legraise.png?v=core-image-fix-1' },
  { id:'pallof-press', name:'Pallof Press', dose:'8 each side', setup:'Stand side-on to an anchored band with both hands at your chest.', cue:'Stand tall and press the band straight out while resisting rotation.', avoid:'Do not let your torso twist toward the band.', easier:'Use a lighter band or stand closer to the anchor.', focus:'Anti-rotation core', art:'pallof', image:'/exercise-pallof.png?v=core-image-fix-1' },
  { id:'split-squat', name:'Bodyweight Split Squat', dose:'8 each side', setup:'Stagger your feet into a comfortable split stance.', cue:'Lower straight down through both legs while keeping your front foot planted.', avoid:'Do not collapse the front knee inward.', easier:'Hold a support or reduce the depth.', focus:'Legs + core', art:'splitsquat', image:'/exercise-splitsquat.png?v=core-image-fix-1' },
  { id:'bulgarian-split-squat', name:'Bulgarian Split Squat', dose:'8 each side', setup:'Place your rear foot on a low, stable bench and set your front foot forward.', cue:'Keep your front foot stable and lower under control with your torso tall.', avoid:'Do not rush the bottom position or let the front knee cave inward.', easier:'Use a floor split squat or hold a support.', focus:'Single-leg strength', art:'bulgarian', image:'/exercise-bulgarian.png?v=core-image-fix-1' },
  { id:'reverse-lunge', name:'Reverse Lunge', dose:'8 each side', setup:'Stand tall with feet about hip-width apart.', cue:'Step back softly and lower until both knees are comfortably bent.', avoid:'Do not let the front knee collapse inward.', easier:'Take a shorter step back or hold a support.', focus:'Legs + balance', art:'reverselunge', image:'/exercise-reverselunge.png?v=core-image-fix-1' },
  { id:'lateral-lunge', name:'Lateral Lunge', dose:'8 each side', setup:'Stand tall with feet together or hip-width apart.', cue:'Step sideways, sit into the outside hip, and keep the other leg long.', avoid:'Do not let the bent knee move inward or the foot lift.', easier:'Take a smaller step and do not sit as low.', focus:'Legs + hips', art:'laterallunge', image:'/exercise-laterallunge.png?v=core-image-fix-1' },
  { id:'step-up', name:'Bodyweight Step-Up', dose:'8 each side', setup:'Face a stable step and place one whole foot on it.', cue:'Place the whole foot on the step and drive through it to stand tall.', avoid:'Do not push off heavily from the trailing leg.', easier:'Use a lower step or hold a support.', focus:'Legs + balance', art:'stepup', image:'/exercise-stepup.png?v=core-image-fix-1' }
];

function Figure({ type }) {
  const c={stroke:'currentColor',strokeWidth:8,fill:'none',strokeLinecap:'round',strokeLinejoin:'round'};
  if(type==='bridge') return <svg viewBox="0 0 320 190"><line x1="20" y1="160" x2="300" y2="160" {...c}/><circle cx="78" cy="130" r="18" {...c}/><path d="M96 132 L150 105 L220 118 L260 157 M150 105 L188 157" {...c}/></svg>;
  if(type==='birddog') return <svg viewBox="0 0 320 190"><line x1="20" y1="160" x2="300" y2="160" {...c}/><circle cx="128" cy="86" r="17" {...c}/><path d="M145 98 L182 120 L224 122 M180 121 L160 158 M224 122 L247 158 M154 110 L102 128 L56 105 M158 111 L208 88 L260 62" {...c}/></svg>;
  if(type==='sideplank') return <svg viewBox="0 0 320 190"><line x1="20" y1="160" x2="300" y2="160" {...c}/><circle cx="90" cy="74" r="17" {...c}/><path d="M108 84 L148 105 L202 128 L244 158 M148 105 L114 149 M202 128 L184 158 M147 104 L164 63" {...c}/></svg>;
  if(type==='heeltap') return <svg viewBox="0 0 320 190"><line x1="20" y1="160" x2="300" y2="160" {...c}/><circle cx="84" cy="128" r="18" {...c}/><path d="M102 129 L150 116 L192 130 M150 116 L146 78 L190 78 M192 130 L248 157 M190 78 L224 112 L214 157" {...c}/></svg>;
  return <svg viewBox="0 0 320 190"><line x1="20" y1="160" x2="300" y2="160" {...c}/><circle cx="83" cy="130" r="18" {...c}/><path d="M101 130 L151 120 L191 120 M149 121 L122 70 M149 121 L186 71 M191 120 L223 83 L252 56 M191 120 L230 151 L280 151" {...c}/></svg>;
}

function deviceId(){let id=localStorage.getItem('core-trainer-device');if(!id){id=crypto.randomUUID();localStorage.setItem('core-trainer-device',id)}return id}
function dateKey(date){return `${date.getFullYear()}-${date.getMonth()}-${date.getDate()}`}
function getConsistency(history){const days=new Set(history.map(item=>dateKey(new Date(item.completedAt))));const today=new Date();let week=0;for(let i=0;i<7;i++){const day=new Date(today);day.setDate(today.getDate()-i);if(days.has(dateKey(day)))week++}let cursor=new Date(today);if(!days.has(dateKey(cursor)))cursor.setDate(cursor.getDate()-1);let streak=0;while(days.has(dateKey(cursor))){streak++;cursor.setDate(cursor.getDate()-1)}return {streak,week}}

export default function Home(){
  const [screen,setScreen]=useState('home'); const [index,setIndex]=useState(0); const [history,setHistory]=useState([]); const [installPrompt,setInstallPrompt]=useState(null); const [timerSeconds,setTimerSeconds]=useState(null); const [timerRunning,setTimerRunning]=useState(false); const [timerRound,setTimerRound]=useState(1); const [timerComplete,setTimerComplete]=useState(false); const [paused,setPaused]=useState(false);
  const current=exercises[index]; const progress=useMemo(()=>Math.round(((index+1)/exercises.length)*100),[index]);
  const consistency=useMemo(()=>getConsistency(history),[history]);
  useEffect(()=>{const h=e=>{e.preventDefault();setInstallPrompt(e)};window.addEventListener('beforeinstallprompt',h);const id=deviceId();fetch(`/api/progress?device=${encodeURIComponent(id)}`).then(r=>r.ok?r.json():{history:[]}).then(d=>setHistory(d.history||[])).catch(()=>{});return()=>window.removeEventListener('beforeinstallprompt',h)},[]);
  useEffect(()=>{setTimerSeconds(current.timer??null);setTimerRunning(false);setTimerRound(1);setTimerComplete(false);setPaused(false)},[index,current.timer]);
  useEffect(()=>{if(!timerRunning||paused)return;const id=setInterval(()=>{setTimerSeconds(value=>{if(value<=1){setTimerRunning(false);if(timerRound<current.timerRounds){setTimerRound(round=>round+1)}else{setTimerComplete(true)}return 0}return value-1})},1000);return()=>clearInterval(id)},[timerRunning,paused,timerRound,current.timerRounds]);
  async function install(){if(installPrompt){await installPrompt.prompt();setInstallPrompt(null)}else alert('Chrome has not offered app installation yet. Refresh this page, then open Chrome’s ⋮ menu and choose “Install app” — not “Add to Home screen”.')}
  async function finish(){const entry={completedAt:new Date().toISOString(),exercises:exercises.length};setHistory(h=>[entry,...h]);setIndex(0);setPaused(false);setScreen('done');fetch('/api/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({device:deviceId(),exercises:exercises.length})}).catch(()=>{})}
  function next(){if(index===exercises.length-1) finish(); else {setPaused(false);setIndex(i=>i+1)}}
  function startTimer(){if(!current.timer||timerComplete)return;setTimerSeconds(current.timer);setTimerRunning(true)}
  function resetTimer(){setTimerSeconds(current.timer??null);setTimerRunning(false);setTimerRound(1);setTimerComplete(false)}
  function previous(){setPaused(false);setIndex(i=>Math.max(0,i-1))}
  function restartWorkout(){setPaused(false);setIndex(0);setScreen('workout')}
  const timerLabel=timerComplete?'Complete':timerRunning?'Running':timerRound>1?'Start side 2':'Start timer';
  return <main className="shell"><header className="topbar"><div><div className="eyebrow">CORE TRAINER</div><h1>Strong core. Simple steps.</h1></div><button className="ghost" onClick={install}>Install app</button></header>
  {screen==='home'&&<section className="stack"><div className="hero card"><div><span className="pill">Beginner • Full movement session</span><h2>Today’s Core Session</h2><p>A complete movement session for trunk stability, glutes, legs and abdominal control.</p></div><button className="primary" onClick={()=>{setIndex(0);setPaused(false);setScreen('workout')}}>Start workout</button></div><div className="grid2"><button className="card actionCard" onClick={()=>setScreen('library')}><strong>Exercise library</strong><span>See all movements and pictures</span></button><button className="card actionCard" onClick={()=>setScreen('progress')}><strong>Progress</strong><span>{consistency.streak} day streak · {consistency.week}/7 this week</span></button></div><div className="note">Move in a comfortable range. Stop if an exercise causes sharp pain, numbness, weakness or worsening back/leg symptoms.</div></section>}
  {screen==='workout'&&<section className="workout card"><div className="row"><button className="textButton" onClick={()=>{setPaused(false);setScreen('home')}}>← Exit</button><span>{index+1} / {exercises.length}</span></div><div className="progress"><span style={{width:`${progress}%`}}/></div><div className="figure"><img className="exerciseImage" src={current.image} alt={`${current.name} start and finish positions`} style={{width:"100%",height:"auto",display:"block"}} /><span className="figureLabel startLabel">Start</span><span className="figureLabel finishLabel">Finish</span></div>{current.timer&&<div className={`timerBox${timerComplete?' complete':''}`}><div><span className="timerLabel">{timerComplete?'Time complete':'Timer'}{current.timerRounds>1&&!timerComplete?` · side ${timerRound} of ${current.timerRounds}`:''}</span><strong>{String(timerSeconds??current.timer).padStart(2,'0')}<small>s</small></strong></div><div className="timerActions"><button className="timerButton" onClick={startTimer} disabled={timerRunning||timerComplete}>{timerLabel}</button>{(timerRunning||timerComplete||timerRound>1)&&<button className="timerReset" onClick={resetTimer}>Reset</button>}</div></div>}<div className="exerciseMeta"><span className="pill">{current.focus}</span><span className="dose">{current.dose}</span></div><h2>{current.name}</h2><div className="instruction setup"><b>Setup</b><p>{current.setup}</p></div><div className="instruction"><b>Do this</b><p>{current.cue}</p></div><div className="instruction warning"><b>Avoid</b><p>{current.avoid}</p></div><div className="instruction easier"><b>Make it easier</b><p>{current.easier}</p></div><button className="primary" onClick={next}>{index===exercises.length-1?'Finish workout':'Done — next exercise'}</button><div className="workoutControls"><button className="controlButton" onClick={previous} disabled={index===0}>Previous</button><button className="controlButton" onClick={()=>setPaused(true)}>Pause</button><button className="controlButton" onClick={next}>Skip</button></div>{paused&&<div className="pausePanel" role="dialog" aria-label="Workout paused"><h3>Workout paused</h3><p>Your progress is saved on this screen.</p><button className="primary" onClick={()=>setPaused(false)}>Resume workout</button><button className="secondaryButton" onClick={restartWorkout}>Restart workout</button><button className="textButton" onClick={()=>{setPaused(false);setScreen('home')}}>Exit workout</button></div>}</section>}
  {screen==='library'&&<section className="stack"><div className="row"><h2>Exercise library</h2><button className="textButton" onClick={()=>setScreen('home')}>Home</button></div>{exercises.map(ex=><article className="card library" key={ex.id}><div className="thumb"><img className="exerciseImage" src={ex.image} alt="" style={{width:"100%",height:"auto",display:"block"}} /></div><div><span className="pill">{ex.focus}</span><h3>{ex.name}</h3><p>{ex.cue}</p><b>{ex.dose}</b></div></article>)}</section>}
  {screen==='progress'&&<section className="stack"><div className="row"><h2>Progress</h2><button className="textButton" onClick={()=>setScreen('home')}>Home</button></div><div className="card statsGrid"><div><div className="bigNumber">{history.length}</div><p>completed workouts</p></div><div><div className="statNumber">{consistency.streak}</div><p>day streak</p></div><div><div className="statNumber">{consistency.week}/7</div><p>days this week</p></div></div>{history.length===0?<div className="note">Complete your first workout and your consistency will appear here.</div>:history.map((h,i)=><div className="history" key={i}><b>{new Date(h.completedAt).toLocaleDateString()}</b><span>{h.exercises||5} exercises</span></div>)}</section>}
  {screen==='done'&&<section className="center card"><div className="check">✓</div><h2>Workout complete</h2><p>You finished all {exercises.length} exercises.</p><button className="primary" onClick={()=>setScreen('home')}>Back home</button></section>}</main>
}
