'use client';

import { useEffect, useMemo, useState } from 'react';

const exercises = [
  { id:'dead-bug', name:'Dead Bug', dose:'6 each side', focus:'Deep core', cue:'Keep your lower back gently heavy against the floor. Move slowly.', avoid:'Do not let the lower back arch as your arm and leg extend.', art:'deadbug', image:'/exercise-deadbug.png' },
  { id:'glute-bridge', name:'Glute Bridge', dose:'10 reps', focus:'Glutes + core', cue:'Brace lightly, squeeze your glutes, then lift until your body forms a straight line.', avoid:'Do not finish by over-arching your lower back.', art:'bridge', image:'/exercise-bridge.png' },
  { id:'bird-dog', name:'Bird Dog', dose:'6 each side', focus:'Core stability', cue:'Reach long through the opposite arm and leg while keeping your hips level.', avoid:'Do not rotate your pelvis or crank your leg too high.', art:'birddog', image:'/exercise-birddog.png' },
  { id:'side-plank-knees', name:'Side Plank — Knees', dose:'20 sec each side', focus:'Side core', cue:'Keep shoulders, hips and knees in one line. Lift from the underside waist.', avoid:'Do not let the top shoulder roll forward.', art:'sideplank', image:'/exercise-sideplank.png' },
  { id:'forearm-plank', name:'Forearm Plank', dose:'20 sec', focus:'Core stability', cue:'Press the forearms into the mat and keep your body in one straight line.', avoid:'Do not let your hips sag or pike upward.', art:'plank', image:'/exercise-plank.png' },
  { id:'crunch', name:'Abdominal Crunch', dose:'10 reps', focus:'Abdominal control', cue:'Curl your upper back gently while keeping your neck relaxed and chin slightly tucked.', avoid:'Do not pull on your neck or use momentum.', art:'crunch', image:'/exercise-crunch.png' },
  { id:'hollow-hold', name:'Hollow Hold', dose:'20 sec', focus:'Deep core', cue:'Keep your ribs down and hold the position without letting your lower back lift.', avoid:'Bend your knees or shorten the lever if your back arches.', art:'hollowhold', image:'/exercise-hollowhold.png' },
  { id:'lying-leg-raise', name:'Lying Leg Raise', dose:'8 reps', focus:'Lower abs', cue:'Lower straight legs slowly while keeping your lower back controlled against the mat.', avoid:'Do not swing your legs or arch your lower back.', art:'legraise', image:'/exercise-legraise.png' },
  { id:'pallof-press', name:'Pallof Press', dose:'8 each side', focus:'Anti-rotation core', cue:'Stand tall and press the band straight out while resisting rotation.', avoid:'Do not let your torso twist toward the band.', art:'pallof', image:'/exercise-pallof.png' },
  { id:'split-squat', name:'Bodyweight Split Squat', dose:'8 each side', focus:'Legs + core', cue:'Lower straight down through both legs while keeping your front foot planted.', avoid:'Do not collapse the front knee inward.', art:'splitsquat', image:'/exercise-splitsquat.png' },
  { id:'bulgarian-split-squat', name:'Bulgarian Split Squat', dose:'8 each side', focus:'Single-leg strength', cue:'Keep your front foot stable and lower under control with your torso tall.', avoid:'Do not rush the bottom position or let the front knee cave inward.', art:'bulgarian', image:'/exercise-bulgarian.png' },
  { id:'reverse-lunge', name:'Reverse Lunge', dose:'8 each side', focus:'Legs + balance', cue:'Step back softly and lower until both knees are comfortably bent.', avoid:'Do not let the front knee collapse inward.', art:'reverselunge', image:'/exercise-reverselunge.png' },
  { id:'lateral-lunge', name:'Lateral Lunge', dose:'8 each side', focus:'Legs + hips', cue:'Step sideways, sit into the outside hip, and keep the other leg long.', avoid:'Do not let the bent knee move inward or the foot lift.', art:'laterallunge', image:'/exercise-laterallunge.png' },
  { id:'step-up', name:'Bodyweight Step-Up', dose:'8 each side', focus:'Legs + balance', cue:'Place the whole foot on the step and drive through it to stand tall.', avoid:'Do not push off heavily from the trailing leg.', art:'stepup', image:'/exercise-stepup.png' }
];

function Figure({ type }) {
  const c={stroke:'currentColor',strokeWidth:8,fill:'none',strokeLinecap:'round',strokeLinejoin:'round'};
  if(type==='bridge') return <svg viewBox="0 0 320 190"><line x1="20" y1="160" x2="300" y2="160" {...c}/><circle cx="78" cy="130" r="18" {...c}/><path d="M96 132 L150 105 L220 118 L260 157 M150 105 L188 157" {...c}/></svg>;
  if(type==='birddog') return <svg viewBox="0 0 320 190"><line x1="20" y1="160" x2="300" y2="160" {...c}/><circle cx="128" cy="86" r="17" {...c}/><path d="M145 98 L182 120 L224 122 M180 121 L160 158 M224 122 L247 158 M154 110 L102 128 L56 105 M158 111 L208 88 L260 62" {...c}/></svg>;
  if(type==='sideplank') return <svg viewBox="0 0 320 190"><line x1="20" y1="160" x2="300" y2="160" {...c}/><circle cx="90" cy="74" r="17" {...c}/><path d="M108 84 L148 105 L202 128 L244 158 M148 105 L114 149 M202 128 L184 158 M147 104 L164 63" {...c}/></svg>;
  if(type==='heeltap') return <svg viewBox="0 0 320 190"><line x1="20" y1="160" x2="300" y2="160" {...c}/><circle cx="84" cy="128" r="18" {...c}/><path d="M102 129 L150 116 L192 130 M150 116 L146 78 L190 78 M192 130 L248 157 M190 78 L224 112 L214 157" {...c}/></svg>;
  return <svg viewBox="0 0 320 190"><line x1="20" y1="160" x2="300" y2="160" {...c}/><circle cx="83" cy="130" r="18" {...c}/><path d="M101 130 L151 120 L191 120 M149 121 L122 70 M149 121 L186 71 M191 120 L223 83 L252 56 M191 120 L230 151 L280 151" {...c}/></svg>;
}

function deviceId(){let id=localStorage.getItem('core-trainer-device');if(!id){id=crypto.randomUUID();localStorage.setItem('core-trainer-device',id)}return id}

export default function Home(){
  const [screen,setScreen]=useState('home'); const [index,setIndex]=useState(0); const [history,setHistory]=useState([]); const [installPrompt,setInstallPrompt]=useState(null);
  const current=exercises[index]; const progress=useMemo(()=>Math.round(((index+1)/exercises.length)*100),[index]);
  useEffect(()=>{const h=e=>{e.preventDefault();setInstallPrompt(e)};window.addEventListener('beforeinstallprompt',h);const id=deviceId();fetch(`/api/progress?device=${encodeURIComponent(id)}`).then(r=>r.ok?r.json():{history:[]}).then(d=>setHistory(d.history||[])).catch(()=>{});return()=>window.removeEventListener('beforeinstallprompt',h)},[]);
  async function install(){if(installPrompt){await installPrompt.prompt();setInstallPrompt(null)}else alert('In Chrome, open the ⋮ menu and choose “Install app” or “Add to Home screen”.')}
  async function finish(){const entry={completedAt:new Date().toISOString(),exercises:exercises.length};setHistory(h=>[entry,...h]);setIndex(0);setScreen('done');fetch('/api/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({device:deviceId(),exercises:exercises.length})}).catch(()=>{})}
  function next(){if(index===exercises.length-1) finish(); else setIndex(i=>i+1)}
  return <main className="shell"><header className="topbar"><div><div className="eyebrow">CORE TRAINER</div><h1>Strong core. Simple steps.</h1></div><button className="ghost" onClick={install}>Install</button></header>
  {screen==='home'&&<section className="stack"><div className="hero card"><div><span className="pill">Beginner • Full movement session</span><h2>Today’s Core Session</h2><p>A complete movement session for trunk stability, glutes, legs and abdominal control.</p></div><button className="primary" onClick={()=>{setIndex(0);setScreen('workout')}}>Start workout</button></div><div className="grid2"><button className="card actionCard" onClick={()=>setScreen('library')}><strong>Exercise library</strong><span>See all movements and pictures</span></button><button className="card actionCard" onClick={()=>setScreen('progress')}><strong>Progress</strong><span>{history.length} workouts completed</span></button></div><div className="note">Move in a comfortable range. Stop if an exercise causes sharp pain, numbness, weakness or worsening back/leg symptoms.</div></section>}
  {screen==='workout'&&<section className="workout card"><div className="row"><button className="textButton" onClick={()=>setScreen('home')}>← Exit</button><span>{index+1} / {exercises.length}</span></div><div className="progress"><span style={{width:`${progress}%`}}/></div><div className="figure"><img src={current.image} alt={`${current.name} start and finish positions`} /></div><div className="exerciseMeta"><span className="pill">{current.focus}</span><span className="dose">{current.dose}</span></div><h2>{current.name}</h2><div className="instruction"><b>Do this</b><p>{current.cue}</p></div><div className="instruction warning"><b>Avoid</b><p>{current.avoid}</p></div><button className="primary" onClick={next}>{index===exercises.length-1?'Finish workout':'Done — next exercise'}</button></section>}
  {screen==='library'&&<section className="stack"><div className="row"><h2>Exercise library</h2><button className="textButton" onClick={()=>setScreen('home')}>Home</button></div>{exercises.map(ex=><article className="card library" key={ex.id}><div className="thumb"><img src={ex.image} alt="" /></div><div><span className="pill">{ex.focus}</span><h3>{ex.name}</h3><p>{ex.cue}</p><b>{ex.dose}</b></div></article>)}</section>}
  {screen==='progress'&&<section className="stack"><div className="row"><h2>Progress</h2><button className="textButton" onClick={()=>setScreen('home')}>Home</button></div><div className="card"><div className="bigNumber">{history.length}</div><p>completed workouts</p></div>{history.length===0?<div className="note">Complete your first workout and it will appear here.</div>:history.map((h,i)=><div className="history" key={i}><b>{new Date(h.completedAt).toLocaleDateString()}</b><span>{h.exercises||5} exercises</span></div>)}</section>}
  {screen==='done'&&<section className="center card"><div className="check">✓</div><h2>Workout complete</h2><p>You finished all {exercises.length} exercises.</p><button className="primary" onClick={()=>setScreen('home')}>Back home</button></section>}</main>
}
